### ISSUE TITLE
module not published on forge

### ISSUE THREAD

**Issue by neoice** [pulp/puppet_deployment#14]
https://github.com/pulp/puppet_deployment/blob/master/metadata.json#L2

    % puppet module install pulp-pulp
    Error: Could not install 'pulp-pulp' (latest)
      No releases are available from https://forgeapi.puppetlabs.com
        Does 'pulp-pulp' have at least one published release?

`jcline/pulp` is older than 45751ae90f1edb530f9c03760a846b99b9ee0a3b for sure. I want to start tracking upstream again instead of running off an internal fork :smile:

**Comment by jeremycline** [comment]
It's finally been uploaded to https://forge.puppetlabs.com/pulp/pulp

Sorry this took so long. I'll do my best to make sure it's updated regularly.
